# Purposefully restricted to ASCII letters.
# Using a list of tuples instead of a dictionary lets me splice to get all mappings 'between' two letters.
MORSE = [
	('.-', 'a'),
	('-...', 'b'),
	('-.-.', 'c'),
	('-..', 'd'),
	('.', 'e'),
	('..-.', 'f'),
	('--.', 'g'),
	('....', 'h'),
	('..', 'i'),
	('.---', 'j'),
	('-.-', 'k'),
	('.-..', 'l'),
	('--', 'm'),
	('-.', 'n'),
	('---', 'o'),
	('.--.', 'p'),
	('--.-', 'q'),
	('.-.', 'r'),
	('...', 's'),
	('-', 't'),
	('..-', 'u'),
	('...-', 'v'),
	('.--', 'w'),
	('-..-', 'x'),
	('-.--', 'y'),
	('--..', 'z')
]
